### ISSUE TITLE
[META 882] Check classic and OTel agents against serverless

### ISSUE THREAD

**Issue by obltmachine** [elastic/elastic-otel-dotnet#134]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/882
- Spec issue: https://github.com/elastic/apm/issues/883

**Comment by stevejgordon** [comment]
Tested successfully using the ApiKey `Authorization` header copied directly from the Serverless APM UI. Tested using a code-based configuration as well as when setting the applicable OTLP environment variable.
