### ISSUE TITLE
 Default metrics dashboards

### ISSUE THREAD

**Issue by estolfo** [elastic/elastic-otel-dotnet#84]
Let's make sure metrics dashboards are shown for the OTel distro in the Metrics tab and that the metrics shown are meaningful. This task might also require some UI task coordination and portable dashboard work.
If work was done for [this issue](https://github.com/elastic/apm/issues/806), it's possible some of it could be reused.

**Comment by stevejgordon** [comment]
Dupe of #58?

**Comment by estolfo** [comment]
duplicate of #59
