### ISSUE TITLE
APM libraries and this library

### ISSUE THREAD

**Issue by juliankock** [elastic/elastic-otel-dotnet#88]
Hey Elastic!

Thanks for bridging the gap between OpenTelemetry and the native features of ElasticSearch telemetry. 

I stumbled upon this repository, and I have been battling a lot with how to configure apps correctly.

Currently, we use Serilog, with the [`EcsTextFormatter`](https://www.nuget.org/packages/Elastic.CommonSchema.Serilog/) and the [APM Serilog enricher](https://www.nuget.org/packages/Elastic.Apm.SerilogEnricher) with the [Serilog console sink](https://github.com/serilog/serilog-sinks-console) in our k8s pods, which gets picked up by a Filebeat scraping the `stdout` of the containers and with [manual instrumentation of APM](https://github.com/elastic/apm-agent-dotnet).

All of our application code currently uses the MEL `ILogger<T>`, with `Serilog` behind the scenes, and we also use [message templates](https://messagetemplates.org/) across our solutions.

I was wondering, since I don't seem like I can find any example that shows this. How do these APM libraries, and this library, cooperate? Is it either this, or the APM library? 

I look forward to hearing from you.

**Comment by Mpdreamz** [comment]
Hey @juliankock thanks for opening this conversation. 

We'll continue to support the `Elastic.Ingest.*` and `Elastic.CommonSchema.*` libraries. 

They remain super useful for logging to file and having `filebeat`/`Elastic Agent` pick them up. Or when you want to write data directly to Elasticsearch. 

With OTLP logs ECS and Semantic Conventions are merging and so we'll continue the ensure structured logging is a first class citizen in this setup as well. 

Most likely the APM correlation libraries as part of `ecs-dotnet` will be deprecated in the long run though.

**Comment by stevejgordon** [comment]
Closing as answered.
